# Configuration SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=driverhub_sql;encrypt=true;trustServerCertificate=true
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=300000
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=CH
spring.datasource.password=Chaimaa#2026SecureA1

# JPA
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
